
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SUNARI
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        txsetor.setVisible(false);
        btsetor.setVisible(false);
        txtarik.setVisible(false);
        bttarik.setVisible(false);
        tpen.setVisible(false);
    }
    String str, str1;
        int choice, z,pin=1234,counter=0,a=3;
        int t,s,tab=50000;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        penarikan = new javax.swing.JButton();
        penyetoran = new javax.swing.JButton();
        informasi = new javax.swing.JButton();
        petunjuk = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        infsaldo = new javax.swing.JLabel();
        txsetor = new javax.swing.JTextField();
        btsetor = new javax.swing.JButton();
        txtarik = new javax.swing.JTextField();
        bttarik = new javax.swing.JButton();
        tpen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BANK NEGARA TELKOM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setText("Jln Danau Ranau Raya. Malang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penarikan.setText("Penarikan");
        penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikanActionPerformed(evt);
            }
        });
        jPanel1.add(penarikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        penyetoran.setText("Penyetoran");
        penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyetoranActionPerformed(evt);
            }
        });
        jPanel1.add(penyetoran, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        informasi.setText("Informasi Saldo");
        informasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informasiActionPerformed(evt);
            }
        });
        jPanel1.add(informasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        petunjuk.setText("Petunjuk");
        petunjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petunjukActionPerformed(evt);
            }
        });
        jPanel1.add(petunjuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, -1));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, -1));
        jPanel1.add(infsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 20));
        jPanel1.add(txsetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        btsetor.setText("OKE");
        btsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsetorActionPerformed(evt);
            }
        });
        jPanel1.add(btsetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 60, -1));
        jPanel1.add(txtarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, -1));

        bttarik.setText("OKE");
        bttarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttarikActionPerformed(evt);
            }
        });
        jPanel1.add(bttarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 60, -1));

        tpen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tpen.setText("<html>\n<p>Cara Penggunaan Aplikasi<br>[1] Masukkan PIN dengan benar<br>[2] Bertransaksilah dengan benar sesuai pilihan<br>[3] Gunakan Uang sesuai kebutuhan rajinlah menabung<br> \"</p>\n<html>");
        jPanel1.add(tpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 420, 250));

        setBounds(0, 0, 535, 372);
    }// </editor-fold>//GEN-END:initComponents

    private void informasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informasiActionPerformed
        // TODO add your handling code here:
       infsaldo.setText("Rp"+ tab);
       home.this.revalidate();
    }//GEN-LAST:event_informasiActionPerformed

    private void penyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyetoranActionPerformed
        // TODO add your handling code here:
        txsetor.setVisible(true);
        btsetor.setVisible(true);
        
        home.this.revalidate();
        home.this.repaint();
        
    }//GEN-LAST:event_penyetoranActionPerformed

    private void btsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsetorActionPerformed
        // TODO add your handling code here:
        int hasil, saldo;
        int s = Integer.parseInt(txsetor.getText());
        
        if(s%100!=0){
            JOptionPane.showMessageDialog(null, "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulangi kembali!", "Transaksi Gagal", 0);
        }
        else if(s<50000){
            JOptionPane.showMessageDialog(null, "Besaran minimal setor jumlah tunai adalah Rp.50000,00", "ERROR", 0);
        }
        else if(s>=50000){
            tab += s;
            JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : " + tab);
            infsaldo.setText("Rp"+ tab);
        }
        
        txsetor.setVisible(false);
        btsetor.setVisible(false);
        
    }//GEN-LAST:event_btsetorActionPerformed

    private void penarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikanActionPerformed
        // TODO add your handling code here:
        txtarik.setVisible(true);
        bttarik.setVisible(true);
        
        home.this.revalidate();
        home.this.repaint();
    }//GEN-LAST:event_penarikanActionPerformed

    private void bttarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttarikActionPerformed
        // TODO add your handling code here:
        int t = Integer.parseInt(txtarik.getText());
        
        
            if(t>tab)
                JOptionPane.showMessageDialog(null, "Saldo Anda tidak mencukupi \nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
            else if(t<50000)
            JOptionPane.showMessageDialog(null, "Besaran minimal pengabilan tunai adalah Rp.50000,00", "ERROR", 0);
            
            else{
                tab = tab -t;
                JOptionPane.showMessageDialog(null, "Saldo Anda saat ini sebesar : " + tab);
                infsaldo.setText("Rp"+tab);
                if(tab<=50000)
                    JOptionPane.showMessageDialog(null, "Saldo minimal harus Rp 50000,00, Segera lakukan penyetoran untuk menghindari penutupan akun", "CAUTION",2);
        }
            
        bttarik.setVisible(false);
        txtarik.setVisible(false);
        
    }//GEN-LAST:event_bttarikActionPerformed

    private void petunjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petunjukActionPerformed
        // TODO add your handling code here:
        tpen.setVisible(true);
        home.this.revalidate();
        home.this.repaint();
    }//GEN-LAST:event_petunjukActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsetor;
    private javax.swing.JButton bttarik;
    private javax.swing.JButton informasi;
    private javax.swing.JLabel infsaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton penarikan;
    private javax.swing.JButton penyetoran;
    private javax.swing.JButton petunjuk;
    private javax.swing.JLabel tpen;
    private javax.swing.JTextField txsetor;
    private javax.swing.JTextField txtarik;
    // End of variables declaration//GEN-END:variables
}
